In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

***1. Data Cleaning and Preprocessing***

In [ ]:
#Load the dataset
df = pd.read_csv('/content/bank-full.csv',sep=";")

In [ ]:
df.head(5)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [ ]:
df.shape

(45211, 17)

In [ ]:
#Identify missing values
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
#IF Missing contain in dataset Handle Missing Values
#num_cols = df.select_dtypes(include=["int64",float64]).columns
#cat_cols = df.select_dtypes(include=["object"]).columns

#Numeric Missing values
#df[num_cols] = df[num_cols].fillna(df[num_cols].median())

#Categorical missing values
#for col in cat_cols:
#  df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
#Check duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
#If duplicates exist:
#df = df.drop_duplicates()

In [ ]:
#Standardize Categorical Columns
cat_cols = df.select_dtypes(include=["object"]).columns

for col in cat_cols:
  df[col] = df[col].str.strip().str.lower()

In [ ]:
#Check Standardize columns
for col in cat_cols:
  print(col, df[col].unique()[:10])

job ['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed']
marital ['married' 'single' 'divorced']
education ['tertiary' 'secondary' 'unknown' 'primary']
default ['no' 'yes']
housing ['yes' 'no']
loan ['no' 'yes']
contact ['unknown' 'cellular' 'telephone']
month ['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar']
poutcome ['unknown' 'failure' 'other' 'success']
y ['no' 'yes']

In [ ]:
#Encode Target Variable (y)
df["y"] = df["y"].map({
    "no":0,
    "yes":1
})
print(df["y"].value_counts())

y
0    39922
1     5289
Name: count, dtype: int64

In [ ]:
#Check Result:
print("Missing values: ")
print(df.isnull().sum())

print("\nTarget distribution: ")
print(df["y"].value_counts())

print("\nFinal dataset: ")
print(df.head())

Missing values:
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

Target distribution:
y
0    39922
1     5289
Name: count, dtype: int64

Final dataset:
   age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no
1   44    technician   single  secondary      no       29     yes   no
2   33  entrepreneur  married  secondary      no        2     yes  yes
3   47   blue-collar  married    unknown      no     1506     yes   no
4   33       unknown   single    unknown      no        1      no   no

   contact  day month  duration  campaign  pdays  previous poutcome  y
0  unknown    5   may       261         1     -1         0  unknown  0
1  unknown    5   may       151         1     -1         0  unknown  0
2  unknown    5   may        76         1     -1         0  unknown  0
3  unknown    5   may        92         1     -1         0  unknown  0
4  unknown    5   may       198         1     -1         0  unknown  0

In [ ]:
df.to_csv(
    '/content/bank_cleaned.csv',
    index=False
)